vscode:
  extensions:
    - vscode-icons-team.vscode-icons@10.2.0:DrQUJPtFm0woSFiyitha8Q==
    - zhuangtongfa.material-theme@3.8.7:tVwESDhtrhU0R/8zhaObjg==
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==